name: webtop
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Webtop"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21166"
        protocol: tcp
      - target: 3001
        published: "21167"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webtop/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.webtop
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: webtop
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/webtop.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/webtop.png
  title:
    en_US: "Webtop"
  tagline:
    en_US: "Webtop (LinuxServer.io)"
  description:
    en_US: "Webtop — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/webtop:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-webtop/"
  port_map: "21166"
  index: /
