name: sonarr
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8989
        published: "8989"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sonarr/config
        target: /config
      - type: bind
        source: /DATA/Media/TV
        target: /tv
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "8989"
          description:
            en_US: Port 8989/tcp
      volumes:
        - container: /config
          description:
            en_US: /config
        - container: /tv
          description:
            en_US: /tv
        - container: /downloads
          description:
            en_US: /downloads

x-casaos:
  id: io.github.mrpiracy94.sonarr
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: sonarr
  author: MrStore
  developer: LinuxServer.io
  category: Media
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png
  title:
    en_US: "Sonarr"
  tagline:
    en_US: "Sonarr (LinuxServer.io)"
  description:
    en_US: "Sonarr — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/sonarr:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-sonarr/"
  port_map: "8989"
  index: /
