name: lazylibrarian
services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest@sha256:a2ba951b7a8c54774172ec5bf5f06f960d0d5d52e8321a58bb385850a95794bd
    container_name: lazylibrarian
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 5299
        published: "5299"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lazylibrarian/config
        target: /config
      - type: bind
        source: /DATA/Media/Books
        target: /books
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.lazylibrarian
  version: "1.0.0"
  main: lazylibrarian
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.lazylibrarian/assets/icon.png
  title:
    en_US: "LazyLibrarian"
  port_map: "5299"
  index: /
