name: lazylibrarian
services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest@sha256:0aece56a912e2de1bbc1ec9b3e2a790f04fe73abac17d84b7ba6b071b3a9b549
    container_name: lazylibrarian
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 5299
        published: "5299"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lazylibrarian/config
        target: /config
      - type: bind
        source: /DATA/Media/Books
        target: /books
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.lazylibrarian
  version: "1.0.1"
  main: lazylibrarian
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.lazylibrarian/assets/icon.png
  title:
    en_US: "LazyLibrarian"
  port_map: "5299"
  index: /
