name: uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.5.6@sha256:99286a05eb86191f3f1aab9b537950aa55b958e77d9f7a2385bc9332674e6e00
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3001
        published: "30004"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/uptime-kuma
        target: /app/data
x-casaos:
  id: io.github.mrpiracy94.uptime-kuma
  version: "1.0.1"
  main: uptime-kuma
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.uptime-kuma/assets/icon.png
  title:
    en_US: "Uptime Kuma"
  port_map: "30004"
  index: /
