name: msedge
services:
  msedge:
    image: lscr.io/linuxserver/msedge:latest@sha256:966acffc9d045c787eac006f159e7693e6be62d628144a61a0f86a74422f12be
    container_name: msedge
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Microsoft Edge"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21100"
        protocol: tcp
      - target: 3001
        published: "21101"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/msedge/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.msedge
  version: "1.0.0"
  main: msedge
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.msedge/assets/icon.svg
  title:
    en_US: "Microsoft Edge"
  port_map: "21100"
  index: /
