name: kometa
services:
  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    volumes:
      - type: bind
        source: /DATA/AppData/kometa/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.kometa
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: kometa
  author: MrStore
  developer: LinuxServer.io
  category: Media
  icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/png/kometa.png
  thumbnail: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/png/kometa.png
  title:
    en_US: "Kometa"
  tagline:
    en_US: "Kometa (LinuxServer.io)"
  description:
    en_US: "Kometa — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/kometa:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-kometa/"
  port_map: "0"
  index: /
