name: cloudflared
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: ["tunnel", "--no-autoupdate", "run"]
    environment:
      - "TUNNEL_TOKEN=CHANGE_ME"

x-casaos:
  id: io.github.mrpiracy94.cloudflared
  version: "1.0.1"
  main: cloudflared
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.cloudflared/assets/icon.png
  title:
    en_US: "Cloudflared"
  port_map: "0"
  index: /
