name: dolphin
services:
  dolphin:
    image: lscr.io/linuxserver/dolphin:latest@sha256:7f72b0587ab99dc0d7a112f31aa4241edba40506aec49b7bf22a636f1a39a624
    container_name: dolphin
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Dolphin Emulator"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21042"
        protocol: tcp
      - target: 3001
        published: "21043"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dolphin/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.dolphin
  version: "1.0.0"
  main: dolphin
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.dolphin/assets/icon.png
  title:
    en_US: "Dolphin Emulator"
  port_map: "21042"
  index: /
