name: glances
services:
  glances:
    image: nicolargo/glances:latest-full@sha256:390348d18cbab39d0a1c6adb411b5d113ad67e4dd2e45e16d34a6682ad4d6b6e
    container_name: glances
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
      - "GLANCES_OPT=-w"
    ports:
      - target: 61208
        published: "61208"
        protocol: tcp

x-casaos:
  id: io.github.mrpiracy94.glances
  version: "1.0.2"
  main: glances
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.glances/assets/icon.png
  title:
    en_US: "Glances"
  port_map: "61208"
  index: /
