name: joplin
services:
  joplin:
    image: lscr.io/linuxserver/joplin:latest@sha256:cc784f9d9d9d6a74ed4355c7536638d39a7f95a0209e407150787e7875b44e93
    container_name: joplin
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "APP_PORT=22300"
      - "APP_BASE_URL=http://zimaos.local:22300"
      - "DB_CLIENT=sqlite3"
    ports:
      - target: 22300
        published: "22300"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/joplin/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.joplin
  version: "1.0.1"
  main: joplin
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.joplin/assets/icon.png
  title:
    en_US: "Joplin Server"
  port_map: "22300"
  index: /
