name: vlc
services:
  vlc:
    image: lscr.io/linuxserver/vlc:latest@sha256:058162d12d582effdec15996be0e3fec8055954fbbbc6f755e3143ac7b688808
    container_name: vlc
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=VLC"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21160"
        protocol: tcp
      - target: 3001
        published: "21161"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vlc/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.vlc
  version: "1.0.1"
  main: vlc
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.vlc/assets/icon.svg
  title:
    en_US: "VLC"
  port_map: "21160"
  index: /
