name: limnoria
services:
  limnoria:
    image: lscr.io/linuxserver/limnoria:latest
    container_name: limnoria
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8080
        published: "20006"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/limnoria/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "8080"
          description:
            en_US: Port 8080/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.limnoria
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: limnoria
  author: MrStore
  developer: LinuxServer.io
  category: Social
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/limnoria-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/limnoria-icon.png
  title:
    en_US: "Limnoria"
  tagline:
    en_US: "Limnoria (LinuxServer.io)"
  description:
    en_US: "Limnoria — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/limnoria:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-limnoria/"
  port_map: "20006"
  index: /
