name: rpcs3
services:
  rpcs3:
    image: lscr.io/linuxserver/rpcs3:latest@sha256:b873e0194bf16e893a1eb2b378c31a691e8d882ede98a2c4ae1a9f3511015c9f
    container_name: rpcs3
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=RPCS3"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21132"
        protocol: tcp
      - target: 3001
        published: "21133"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rpcs3/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.rpcs3
  version: "1.0.1"
  main: rpcs3
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.rpcs3/assets/icon.png
  title:
    en_US: "RPCS3"
  port_map: "21132"
  index: /
