name: rpcs3
services:
  rpcs3:
    image: lscr.io/linuxserver/rpcs3:latest@sha256:3708e99810e2b0019d42b665ee1e665fe25fd8d9cfc2e4b4c41d7e73af362f21
    container_name: rpcs3
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=RPCS3"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21132"
        protocol: tcp
      - target: 3001
        published: "21133"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rpcs3/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.rpcs3
  version: "1.0.0"
  main: rpcs3
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.rpcs3/assets/icon.svg
  title:
    en_US: "RPCS3"
  port_map: "21132"
  index: /
