name: hishtory-server
services:
  hishtory-server:
    image: lscr.io/linuxserver/hishtory-server:latest@sha256:067703ba6f4fd7df52d6b4829c471425de17647290a801a2f942d3812c0600f8
    container_name: hishtory-server
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8080
        published: "20051"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/hishtory-server/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.hishtory-server
  version: "1.0.0"
  main: hishtory-server
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.hishtory-server/assets/icon.svg
  title:
    en_US: "hishtory-server"
  port_map: "20051"
  index: /
