name: hishtory-server
services:
  hishtory-server:
    image: lscr.io/linuxserver/hishtory-server:latest
    container_name: hishtory-server
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8080
        published: "20051"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/hishtory-server/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.hishtory-server
  version: "1.0.1"
  main: hishtory-server
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.hishtory-server/assets/icon.png
  title:
    en_US: "hishtory-server"
  port_map: "20051"
  index: /
