name: apprise-api
services:
  apprise-api:
    image: lscr.io/linuxserver/apprise-api:latest@sha256:19b6f979f48efe1a87f8acf4f9609d474bd8067085dbdb80e628e1ce298a9f48
    container_name: apprise-api
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8000
        published: "20038"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/apprise-api/config
        target: /config
      - type: bind
        source: /DATA/AppData/apprise-api/attach
        target: /attach
x-casaos:
  id: io.github.mrpiracy94.apprise-api
  version: "1.0.2"
  main: apprise-api
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.apprise-api/assets/icon.svg
  title:
    en_US: "Apprise API"
  port_map: "20038"
  index: /
