name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest@sha256:9d587fbedab1712186bae480b63a778d1f05d84a8d9b2cdf384c22599575ca68
    container_name: homepage
    restart: unless-stopped
    environment:
      - "HOMEPAGE_ALLOWED_HOSTS=*"
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "30007"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/homepage
        target: /app/config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
x-casaos:
  id: io.github.mrpiracy94.homepage
  version: "1.0.0"
  main: homepage
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.homepage/assets/icon.png
  title:
    en_US: "Homepage"
  port_map: "30007"
  index: /
