name: speedtest-tracker
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest@sha256:e0bbf68d0254e09d457d8b2b5069f3b996fd9c16ba3558e9747dd2923e3db613
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "APP_KEY=base64:CHANGE_ME"
      - "DB_CONNECTION=sqlite"
    ports:
      - target: 80
        published: "20010"
        protocol: tcp
      - target: 443
        published: "20011"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/speedtest-tracker/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.speedtest-tracker
  version: "1.0.1"
  main: speedtest-tracker
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.speedtest-tracker/assets/icon.png
  title:
    en_US: "Speedtest Tracker"
  port_map: "20010"
  index: /
