name: speedtest-tracker
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest@sha256:e4c7c42b65868489aace7a1f4afa108ca4435162428db1898edb11a892f5cb78
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "APP_KEY=base64:CHANGE_ME"
      - "DB_CONNECTION=sqlite"
    ports:
      - target: 80
        published: "20010"
        protocol: tcp
      - target: 443
        published: "20011"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/speedtest-tracker/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.speedtest-tracker
  version: "1.0.0"
  main: speedtest-tracker
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.speedtest-tracker/assets/icon.png
  title:
    en_US: "Speedtest Tracker"
  port_map: "20010"
  index: /
