name: bambustudio
services:
  bambustudio:
    image: lscr.io/linuxserver/bambustudio:latest
    container_name: bambustudio
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Bambu Studio"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21020"
        protocol: tcp
      - target: 3001
        published: "21021"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bambustudio/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.bambustudio
  version: "1.0.1"
  update_at: "2026-10-09"
  architectures:
    - amd64
  main: bambustudio
  author: MrStore
  developer: LinuxServer.io
  category: Productivity
  icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/57e939e504eda0ea764098015da93aa666ad6f31/png/bambu-lab.png
  thumbnail: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/57e939e504eda0ea764098015da93aa666ad6f31/png/bambu-lab.png
  title:
    en_US: "Bambu Studio"
  tagline:
    en_US: "Bambu Studio (LinuxServer.io)"
  description:
    en_US: "Bambu Studio — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/bambustudio:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-bambustudio/"
  port_map: "21020"
  index: /
