name: bitcoin-knots
services:
  bitcoin-knots:
    image: lscr.io/linuxserver/bitcoin-knots:latest@sha256:3816fd7d5e7df5a89938f5b7b689aad64faf24b6a3875435f8950bce7eab8a95
    container_name: bitcoin-knots
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8333
        published: "8333"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bitcoin-knots/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.bitcoin-knots
  version: "1.0.0"
  main: bitcoin-knots
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.bitcoin-knots/assets/icon.svg
  title:
    en_US: "Bitcoin Knots"
  port_map: "0"
  index: /
