name: mame
services:
  mame:
    image: lscr.io/linuxserver/mame:latest@sha256:f5ee370a4cab718983841e3f1c5ab36948b88a7da86195e8e26d57839d4d85c0
    container_name: mame
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=MAME"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21094"
        protocol: tcp
      - target: 3001
        published: "21095"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mame/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.mame
  version: "1.0.1"
  main: mame
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.mame/assets/icon.png
  title:
    en_US: "MAME"
  port_map: "21094"
  index: /
