name: mullvad-browser
services:
  mullvad-browser:
    image: lscr.io/linuxserver/mullvad-browser:latest
    container_name: mullvad-browser
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Mullvad Browser"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21102"
        protocol: tcp
      - target: 3001
        published: "21103"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mullvad-browser/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.mullvad-browser
  version: "1.0.1"
  main: mullvad-browser
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.mullvad-browser/assets/icon.png
  title:
    en_US: "Mullvad Browser"
  port_map: "21102"
  index: /
