name: audiobookshelf
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest@sha256:10f3490855630aa024ba618b90ba6f58f3d9d7063dd77e1d1e958fdc4ede7c70
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "30006"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/audiobookshelf/config
        target: /config
      - type: bind
        source: /DATA/AppData/audiobookshelf/metadata
        target: /metadata
      - type: bind
        source: /DATA/Media/Audiobooks
        target: /audiobooks
      - type: bind
        source: /DATA/Media/Podcasts
        target: /podcasts
x-casaos:
  id: io.github.mrpiracy94.audiobookshelf
  version: "1.0.1"
  main: audiobookshelf
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.audiobookshelf/assets/icon.png
  title:
    en_US: "Audiobookshelf"
  port_map: "30006"
  index: /
