name: orcaslicer
services:
  orcaslicer:
    image: lscr.io/linuxserver/orcaslicer:latest
    container_name: orcaslicer
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=OrcaSlicer"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21112"
        protocol: tcp
      - target: 3001
        published: "21113"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/orcaslicer/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.orcaslicer
  version: "1.0.0"
  main: orcaslicer
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.orcaslicer/assets/icon.png
  title:
    en_US: "OrcaSlicer"
  port_map: "21112"
  index: /
