name: dashy
services:
  dashy:
    image: lissy93/dashy:latest@sha256:d1b6a77d0d61ba7f6ffa9be9842a5993eac725c37a7381671a71339f0f1dbb66
    container_name: dashy
    restart: unless-stopped
    ports:
      - target: 8080
        published: "30008"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dashy
        target: /app/user-data
x-casaos:
  id: io.github.mrpiracy94.dashy
  version: "1.0.0"
  main: dashy
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.dashy/assets/icon.png
  title:
    en_US: "Dashy"
  port_map: "30008"
  index: /
