name: dashy
services:
  dashy:
    image: lissy93/dashy:latest@sha256:41306e58ac4cf2011b1aeac064cb77172b20acf67ae1b8a00e5a0a77de619f3e
    container_name: dashy
    restart: unless-stopped
    ports:
      - target: 8080
        published: "30008"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dashy
        target: /app/user-data
x-casaos:
  id: io.github.mrpiracy94.dashy
  version: "1.0.0"
  main: dashy
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.dashy/assets/icon.png
  title:
    en_US: "Dashy"
  port_map: "30008"
  index: /
