name: radarr
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest@sha256:2fce439bf4e1001b55b58eac915918ed101fa51ed2d396475ecc4c99c70062c2
    container_name: radarr
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 7878
        published: "7878"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/radarr/config
        target: /config
      - type: bind
        source: /DATA/Media/Movies
        target: /movies
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.radarr
  version: "1.0.1"
  main: radarr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.radarr/assets/icon.png
  title:
    en_US: "Radarr"
  port_map: "7878"
  index: /
