name: pelorus
services:
  pelorus:
    image: lscr.io/linuxserver/pelorus:latest@sha256:ba13e4a2fccd931ae8104089f573498fd180fedfce5f20b88b269cafd35fe8af
    container_name: pelorus
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "20057"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pelorus/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.pelorus
  version: "1.0.1"
  main: pelorus
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.pelorus/assets/icon.svg
  title:
    en_US: "Pelorus"
  port_map: "20057"
  index: /
