name: syslog-ng
services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest@sha256:63e1acee513906ef56ea11c782e8615e7f57047a48b8c04aa27be0755a6b7222
    container_name: syslog-ng
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 514
        published: "514"
        protocol: udp
      - target: 601
        published: "601"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/syslog-ng/config
        target: /config
      - type: bind
        source: /DATA/AppData/syslog-ng/log
        target: /var/log
x-casaos:
  id: io.github.mrpiracy94.syslog-ng
  version: "1.0.1"
  main: syslog-ng
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.syslog-ng/assets/icon.svg
  title:
    en_US: "syslog-ng"
  port_map: "0"
  index: /
