name: flaresolverr
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
      - "LOG_LEVEL=info"
    ports:
      - target: 8191
        published: "8191"
        protocol: tcp
x-casaos:
  id: io.github.mrpiracy94.flaresolverr
  version: "1.0.1"
  main: flaresolverr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.flaresolverr/assets/icon.png
  title:
    en_US: "FlareSolverr"
  port_map: "8191"
  index: /
