name: chromium
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest@sha256:138229f3759666bba2571c9c8cd27e1b3b4a63d8256e0ffe552b55e281776f85
    container_name: chromium
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Chromium"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21034"
        protocol: tcp
      - target: 3001
        published: "21035"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/chromium/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.chromium
  version: "1.0.1"
  main: chromium
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.chromium/assets/icon.png
  title:
    en_US: "Chromium"
  port_map: "21034"
  index: /
