name: deluge
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest@sha256:ff73d12900952f8706f7c4f4c0ceb3d0d8b45a632f60c8938346275ba3fc0764
    container_name: deluge
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8112
        published: "8112"
        protocol: tcp
      - target: 6881
        published: "20000"
        protocol: tcp
      - target: 6881
        published: "6882"
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/deluge/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.deluge
  version: "1.0.1"
  main: deluge
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.deluge/assets/icon.png
  title:
    en_US: "Deluge"
  port_map: "8112"
  index: /
