name: wps-office
services:
  wps-office:
    image: lscr.io/linuxserver/wps-office:latest
    container_name: wps-office
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=WPS Office"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21172"
        protocol: tcp
      - target: 3001
        published: "21173"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wps-office/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.wps-office
  version: "1.0.1"
  main: wps-office
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.wps-office/assets/icon.png
  title:
    en_US: "WPS Office"
  port_map: "21172"
  index: /
