name: scummvm
services:
  scummvm:
    image: lscr.io/linuxserver/scummvm:latest
    container_name: scummvm
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=ScummVM"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21134"
        protocol: tcp
      - target: 3001
        published: "21135"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/scummvm/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.scummvm
  version: "1.0.0"
  main: scummvm
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.scummvm/assets/icon.svg
  title:
    en_US: "ScummVM"
  port_map: "21134"
  index: /
