name: gitqlient
services:
  gitqlient:
    image: lscr.io/linuxserver/gitqlient:latest
    container_name: gitqlient
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=GitQlient"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21066"
        protocol: tcp
      - target: 3001
        published: "21067"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gitqlient/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.gitqlient
  version: "1.0.1"
  main: gitqlient
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.gitqlient/assets/icon.svg
  title:
    en_US: "GitQlient"
  port_map: "21066"
  index: /
