name: vscode
services:
  vscode:
    image: lscr.io/linuxserver/vscode:latest
    container_name: vscode
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=VS Code"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21184"
        protocol: tcp
      - target: 3001
        published: "21185"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vscode/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.vscode
  version: "1.0.1"
  main: vscode
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.vscode/assets/icon.png
  title:
    en_US: "VS Code"
  port_map: "21184"
  index: /
