name: cura
services:
  cura:
    image: lscr.io/linuxserver/cura:latest@sha256:a1b289f0b2572591de7e7fd1ce8600e238e807b3d881eb672b4fde9c8327ef3d
    container_name: cura
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Cura"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21036"
        protocol: tcp
      - target: 3001
        published: "21037"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/cura/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.cura
  version: "1.0.0"
  main: cura
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.cura/assets/icon.png
  title:
    en_US: "Cura"
  port_map: "21036"
  index: /
