name: shotcut
services:
  shotcut:
    image: lscr.io/linuxserver/shotcut:latest@sha256:55e38b082051754844fcf21c12735ec8ac5a5bd227ddc6c50f8756ee22039cc1
    container_name: shotcut
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Shotcut"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21140"
        protocol: tcp
      - target: 3001
        published: "21141"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/shotcut/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.shotcut
  version: "1.0.1"
  main: shotcut
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.shotcut/assets/icon.png
  title:
    en_US: "Shotcut"
  port_map: "21140"
  index: /
