name: prowlarr
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest@sha256:20bc5fdf919b4f86f9ab9b46d0f51a3b5d3fa83108819a0e4bbbc7bc2fee11cf
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 9696
        published: "9696"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/prowlarr/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.prowlarr
  version: "1.0.1"
  main: prowlarr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.prowlarr/assets/icon.png
  title:
    en_US: "Prowlarr"
  port_map: "9696"
  index: /
