name: recyclarr
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:8@sha256:9142672a0e6ddfab27158aae5f2f9a08f445237bd10e41421ad2023011ed3363
    container_name: recyclarr
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
      - "CRON_SCHEDULE=@daily"
    volumes:
      - type: bind
        source: /DATA/AppData/recyclarr
        target: /config
x-casaos:
  id: io.github.mrpiracy94.recyclarr
  version: "1.0.2"
  main: recyclarr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.recyclarr/assets/icon.png
  title:
    en_US: "Recyclarr"
  port_map: "0"
  index: /
