name: oscam
services:
  oscam:
    image: lscr.io/linuxserver/oscam:latest@sha256:f90c80a0e3b25db1a55826115923219f9032fa09afb213b2ea570c6579115fc0
    container_name: oscam
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8888
        published: "20052"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/oscam/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.oscam
  version: "1.0.2"
  main: oscam
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.oscam/assets/icon.png
  title:
    en_US: "OSCam"
  port_map: "20052"
  index: /
