name: vivaldi
services:
  vivaldi:
    image: lscr.io/linuxserver/vivaldi:latest@sha256:623067e9a332a8c298ba940a1f81c5c431b7d37b2e41abe269dbffb419247bf0
    container_name: vivaldi
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Vivaldi"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21158"
        protocol: tcp
      - target: 3001
        published: "21159"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.vivaldi
  version: "1.0.1"
  main: vivaldi
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.vivaldi/assets/icon.png
  title:
    en_US: "Vivaldi"
  port_map: "21158"
  index: /
