name: remmina
services:
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Remmina"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21128"
        protocol: tcp
      - target: 3001
        published: "21129"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.remmina
  version: "1.0.0"
  main: remmina
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.remmina/assets/icon.png
  title:
    en_US: "Remmina"
  port_map: "21128"
  index: /
