name: projectsend
services:
  projectsend:
    image: lscr.io/linuxserver/projectsend:latest@sha256:9ca4e58ea4dca3fa237f0be7aa5b5a5d87590aa3b909e686d7b9f667f6ecf897
    container_name: projectsend
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20021"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/projectsend/config
        target: /config
      - type: bind
        source: /DATA/AppData/projectsend/data
        target: /data
x-casaos:
  id: io.github.mrpiracy94.projectsend
  version: "1.0.0"
  main: projectsend
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.projectsend/assets/icon.png
  title:
    en_US: "ProjectSend"
  port_map: "20021"
  index: /
