name: dozzle
services:
  dozzle:
    image: amir20/dozzle:latest@sha256:b10715e3c489c1063a1676ff183db2a36a6f0d25efc25215862796ef786f6022
    container_name: dozzle
    restart: unless-stopped
    ports:
      - target: 8080
        published: "30011"
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  id: io.github.mrpiracy94.dozzle
  version: "1.0.1"
  main: dozzle
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.dozzle/assets/icon.png
  title:
    en_US: "Dozzle"
  port_map: "30011"
  index: /
