name: kali-linux
services:
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest@sha256:72e1147dcf80f9bbeb402d4d76e02a23a53e511eb8916e24346997f1b618fe24
    container_name: kali-linux
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Kali Linux"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21078"
        protocol: tcp
      - target: 3001
        published: "21079"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kali-linux/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.kali-linux
  version: "1.0.1"
  main: kali-linux
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.kali-linux/assets/icon.png
  title:
    en_US: "Kali Linux"
  port_map: "21078"
  index: /
