name: filezilla
services:
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest@sha256:44963709fdfef1f33317287be247888158c64090aea827062a155d51bf59229f
    container_name: filezilla
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=FileZilla"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21054"
        protocol: tcp
      - target: 3001
        published: "21055"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/filezilla/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.filezilla
  version: "1.0.1"
  main: filezilla
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.filezilla/assets/icon.png
  title:
    en_US: "FileZilla"
  port_map: "21054"
  index: /
