name: tdarr
services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest@sha256:e47d0e75ce8b2d68c079c752dc39e26a6357ae71bda32543cc79673657e8afc4
    container_name: tdarr
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "serverIP=0.0.0.0"
      - "serverPort=8266"
      - "webUIPort=8265"
      - "internalNode=true"
      - "nodeName=InternalNode"
    ports:
      - target: 8265
        published: "8265"
        protocol: tcp
      - target: 8266
        published: "8266"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/tdarr/server
        target: /app/server
      - type: bind
        source: /DATA/AppData/tdarr/configs
        target: /app/configs
      - type: bind
        source: /DATA/AppData/tdarr/logs
        target: /app/logs
      - type: bind
        source: /DATA/AppData/tdarr/temp
        target: /temp
      - type: bind
        source: /DATA/Media
        target: /media
x-casaos:
  id: io.github.mrpiracy94.tdarr
  version: "1.0.0"
  main: tdarr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.tdarr/assets/icon.png
  title:
    en_US: "Tdarr"
  port_map: "8265"
  index: /
