name: freshrss
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest@sha256:1a46ce0355094d6167a74f1c9887c6644d6ceea0e848297be89163a9d275c384
    container_name: freshrss
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20032"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freshrss/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.freshrss
  version: "1.0.0"
  main: freshrss
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.freshrss/assets/icon.png
  title:
    en_US: "FreshRSS"
  port_map: "20032"
  index: /
