name: syslog-ng
services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 514
        published: "514"
        protocol: udp
      - target: 601
        published: "601"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/syslog-ng/config
        target: /config
      - type: bind
        source: /DATA/AppData/syslog-ng/log
        target: /var/log
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "514"
          description:
            en_US: Port 514/udp
        - container: "601"
          description:
            en_US: Port 601/tcp
      volumes:
        - container: /config
          description:
            en_US: /config
        - container: /var/log
          description:
            en_US: /var/log

x-casaos:
  id: io.github.mrpiracy94.syslog-ng
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: syslog-ng
  author: MrStore
  developer: LinuxServer.io
  category: Networking
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/syslog-ng-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/syslog-ng-logo.png
  title:
    en_US: "syslog-ng"
  tagline:
    en_US: "syslog-ng (LinuxServer.io)"
  description:
    en_US: "syslog-ng — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/syslog-ng:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-syslog-ng/"
  port_map: "0"
  index: /
