name: boinc
services:
  boinc:
    image: lscr.io/linuxserver/boinc:latest
    container_name: boinc
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=BOINC"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21024"
        protocol: tcp
      - target: 3001
        published: "21025"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/boinc/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.boinc
  version: "1.0.1"
  main: boinc
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.boinc/assets/icon.png
  title:
    en_US: "BOINC"
  port_map: "21024"
  index: /
