name: transmission
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 9091
        published: "9091"
        protocol: tcp
      - target: 51413
        published: "51413"
        protocol: tcp
      - target: 51413
        published: "51413"
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/transmission/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/Downloads/watch
        target: /watch
x-casaos:
  id: io.github.mrpiracy94.transmission
  version: "1.0.0"
  main: transmission
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.transmission/assets/icon.png
  title:
    en_US: "Transmission"
  port_map: "9091"
  index: /
