name: socket-proxy
services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest@sha256:3bf68de5e334fb06a4288d94b1d98dc2bc69a99536f093a3c9c67d313e4883a8
    container_name: socket-proxy
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "CONTAINERS=1"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  id: io.github.mrpiracy94.socket-proxy
  version: "1.0.0"
  main: socket-proxy
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.socket-proxy/assets/icon.svg
  title:
    en_US: "Socket Proxy"
  port_map: "0"
  index: /
