name: grocy
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest@sha256:b511f8c7cc8aac3b586eb4cd9b5d067bdfcb720b668ebdbae23b46c3eb847405
    container_name: grocy
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20034"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grocy/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.grocy
  version: "1.0.1"
  main: grocy
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.grocy/assets/icon.png
  title:
    en_US: "Grocy"
  port_map: "20034"
  index: /
