name: webtop
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest@sha256:d729b300b98a21b975285f923390b5e08d43ee5744544ac036b00b7ccf20e465
    container_name: webtop
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Webtop"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21166"
        protocol: tcp
      - target: 3001
        published: "21167"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webtop/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.webtop
  version: "1.0.0"
  main: webtop
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.webtop/assets/icon.png
  title:
    en_US: "Webtop"
  port_map: "21166"
  index: /
