name: adguardhome-sync
services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest@sha256:08baf3b9c2de297123c382756d4aa335fbd82a2d8bc699a6d0cda8eaf7fa2e33
    container_name: adguardhome-sync
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8080
        published: "20016"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/adguardhome-sync/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.adguardhome-sync
  version: "1.0.2"
  main: adguardhome-sync
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.adguardhome-sync/assets/icon.png
  title:
    en_US: "AdGuardHome Sync"
  port_map: "20016"
  index: /
