name: adguardhome-sync
services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest@sha256:9a53a745f61d4b6a971834633cde82fdd34356fae06e1b23f77281546642ae56
    container_name: adguardhome-sync
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8080
        published: "20016"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/adguardhome-sync/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.adguardhome-sync
  version: "1.0.2"
  main: adguardhome-sync
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.adguardhome-sync/assets/icon.png
  title:
    en_US: "AdGuardHome Sync"
  port_map: "20016"
  index: /
