name: mylar3
services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8090
        published: "8090"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mylar3/config
        target: /config
      - type: bind
        source: /DATA/Media/Comics
        target: /comics
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "8090"
          description:
            en_US: Port 8090/tcp
      volumes:
        - container: /config
          description:
            en_US: /config
        - container: /comics
          description:
            en_US: /comics
        - container: /downloads
          description:
            en_US: /downloads

x-casaos:
  id: io.github.mrpiracy94.mylar3
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: mylar3
  author: MrStore
  developer: LinuxServer.io
  category: Media
  icon: https://raw.githubusercontent.com/mrpiracy94/MrStore/main/Apps/mylar3/icon.svg
  thumbnail: https://raw.githubusercontent.com/mrpiracy94/MrStore/main/Apps/mylar3/icon.svg
  title:
    en_US: "Mylar3"
  tagline:
    en_US: "Mylar3 (LinuxServer.io)"
  description:
    en_US: "Mylar3 — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/mylar3:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-mylar3/"
  port_map: "8090"
  index: /
