name: sabnzbd
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8080
        published: "20001"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sabnzbd/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.sabnzbd
  version: "1.0.1"
  main: sabnzbd
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.sabnzbd/assets/icon.png
  title:
    en_US: "SABnzbd"
  port_map: "20001"
  index: /
