name: chromium
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Chromium"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21034"
        protocol: tcp
      - target: 3001
        published: "21035"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/chromium/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.chromium
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: chromium
  author: MrStore
  developer: LinuxServer.io
  category: Productivity
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/chromium.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/chromium.png
  title:
    en_US: "Chromium"
  tagline:
    en_US: "Chromium (LinuxServer.io)"
  description:
    en_US: "Chromium — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/chromium:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-chromium/"
  port_map: "21034"
  index: /
