name: your_spotify
services:
  your_spotify:
    image: lscr.io/linuxserver/your_spotify:latest@sha256:439452bc145995b881a2e569a0ee5c580f6beccde6445f040556296961156c92
    container_name: your_spotify
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "API_ENDPOINT=http://zimaos.local:8080"
      - "CLIENT_ENDPOINT=http://zimaos.local:8081"
    ports:
      - target: 80
        published: "20056"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/your_spotify/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.your_spotify
  version: "1.0.0"
  main: your_spotify
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.your_spotify/assets/icon.png
  title:
    en_US: "Your Spotify"
  port_map: "20056"
  index: /
