name: telegram
services:
  telegram:
    image: lscr.io/linuxserver/telegram:latest@sha256:439d5053e35ac2eb1d7077e48b603d88e060d34a494e04fef4af96b7ca944291
    container_name: telegram
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Telegram"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21152"
        protocol: tcp
      - target: 3001
        published: "21153"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/telegram/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.telegram
  version: "1.0.1"
  main: telegram
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.telegram/assets/icon.png
  title:
    en_US: "Telegram"
  port_map: "21152"
  index: /
