name: nzbget
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest@sha256:c576ef5ccbee8c4cfb65e963ae10dfdaba7f79007e5e757cf4a349cffc9120a1
    container_name: nzbget
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 6789
        published: "6789"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nzbget/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.nzbget
  version: "1.0.0"
  main: nzbget
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.nzbget/assets/icon.png
  title:
    en_US: "NZBGet"
  port_map: "6789"
  index: /
