name: nzbget
services:
  nzbget:
    image: ghcr.io/mrpiracy94/mrstore-python-nzbget@sha256:9c45c7e1b8b72de8874540a9d9e5a8b9a94c7c0c25b9b88ba3d319120807d8a6
    container_name: nzbget
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 6789
        published: "6789"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nzbget/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.nzbget
  version: "1.0.2"
  main: nzbget
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.nzbget/assets/icon.png
  title:
    en_US: "NZBGet"
  port_map: "6789"
  index: /
