name: keepassxc
services:
  keepassxc:
    image: lscr.io/linuxserver/keepassxc:latest
    container_name: keepassxc
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=KeePassXC"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21082"
        protocol: tcp
      - target: 3001
        published: "21083"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/keepassxc/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.keepassxc
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: keepassxc
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/keepassxc.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/keepassxc.png
  title:
    en_US: "KeePassXC"
  tagline:
    en_US: "KeePassXC (LinuxServer.io)"
  description:
    en_US: "KeePassXC — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/keepassxc:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-keepassxc/"
  port_map: "21082"
  index: /
