name: openssh-server
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "PASSWORD_ACCESS=true"
      - "USER_NAME=admin"
    ports:
      - target: 2222
        published: "2222"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/openssh-server/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "2222"
          description:
            en_US: Port 2222/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.openssh-server
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: openssh-server
  author: MrStore
  developer: LinuxServer.io
  category: Networking
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/openssh-server-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/openssh-server-icon.png
  title:
    en_US: "OpenSSH Server"
  tagline:
    en_US: "OpenSSH Server (LinuxServer.io)"
  description:
    en_US: "OpenSSH Server — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/openssh-server:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-openssh-server/"
  port_map: "2222"
  index: /
