name: yaak
services:
  yaak:
    image: lscr.io/linuxserver/yaak:latest@sha256:9cc4c245e5fd21739159f5d4816379f0b04ed62c15c728b3c86617fc713801d2
    container_name: yaak
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Yaak"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21176"
        protocol: tcp
      - target: 3001
        published: "21177"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yaak/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.yaak
  version: "1.0.0"
  main: yaak
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.yaak/assets/icon.svg
  title:
    en_US: "Yaak"
  port_map: "21176"
  index: /
