name: digikam
services:
  digikam:
    image: lscr.io/linuxserver/digikam:latest
    container_name: digikam
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=digiKam"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21040"
        protocol: tcp
      - target: 3001
        published: "21041"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/digikam/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.digikam
  version: "1.0.2"
  main: digikam
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.digikam/assets/icon.svg
  title:
    en_US: "digiKam"
  port_map: "21040"
  index: /
