name: modrinth
services:
  modrinth:
    image: lscr.io/linuxserver/modrinth:latest
    container_name: modrinth
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Modrinth App"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21004"
        protocol: tcp
      - target: 3001
        published: "21005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/modrinth/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.modrinth
  version: "1.0.1"
  main: modrinth
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.modrinth/assets/icon.png
  title:
    en_US: "Modrinth App"
  port_map: "21004"
  index: /
