name: modmanager
services:
  modmanager:
    image: lscr.io/linuxserver/modmanager:latest
    container_name: modmanager
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Mod Manager"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21002"
        protocol: tcp
      - target: 3001
        published: "21003"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/modmanager/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.modmanager
  version: "1.0.1"
  main: modmanager
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.modmanager/assets/icon.svg
  title:
    en_US: "Mod Manager"
  port_map: "21002"
  index: /
