name: maintainerr
services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:latest@sha256:186ff0aaa5b531f51cf82fa817d7b1d75dbcd71d7be6b013d4bd0f097ae9c570
    container_name: maintainerr
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
    ports:
      - target: 6246
        published: "6246"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/maintainerr
        target: /opt/data
x-casaos:
  id: io.github.mrpiracy94.maintainerr
  version: "1.0.1"
  main: maintainerr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.maintainerr/assets/icon.png
  title:
    en_US: "Maintainerr"
  port_map: "6246"
  index: /
