name: ollama
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - target: 11434
        published: "11434"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ollama
        target: /root/.ollama
x-casaos:
  id: io.github.mrpiracy94.ollama
  version: "1.0.0"
  main: ollama
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.ollama/assets/icon.png
  title:
    en_US: "Ollama"
  port_map: "11434"
  index: /
