name: tailscale
services:
  tailscale:
    image: tailscale/tailscale:latest@sha256:08a1bc6c82fee62d1a135788fb67fefa9d22deea3830e8a45ebe1a3cb116e325
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - "TS_AUTHKEY=CHANGE_ME"
      - "TS_STATE_DIR=/var/lib/tailscale"
      - "TS_USERSPACE=false"
    volumes:
      - type: bind
        source: /DATA/AppData/tailscale
        target: /var/lib/tailscale
      - type: bind
        source: /dev/net/tun
        target: /dev/net/tun
x-casaos:
  id: io.github.mrpiracy94.tailscale
  version: "1.0.0"
  main: tailscale
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.tailscale/assets/icon.png
  title:
    en_US: "Tailscale"
  port_map: "0"
  index: /
