name: ffmpeg
services:
  ffmpeg:
    image: lscr.io/linuxserver/ffmpeg:latest
    container_name: ffmpeg
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    volumes:
      - type: bind
        source: /DATA/AppData/ffmpeg/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /data
x-casaos:
  id: io.github.mrpiracy94.ffmpeg
  version: "1.0.1"
  main: ffmpeg
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.ffmpeg/assets/icon.svg
  title:
    en_US: "FFmpeg"
  port_map: "0"
  index: /
