name: wireshark
services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest@sha256:232b73749f58fe7063fb54deef30a99b1323eb6c1f943f077615c536e29788ff
    container_name: wireshark
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Wireshark"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21170"
        protocol: tcp
      - target: 3001
        published: "21171"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wireshark/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.wireshark
  version: "1.0.1"
  main: wireshark
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.wireshark/assets/icon.png
  title:
    en_US: "Wireshark"
  port_map: "21170"
  index: /
