name: webgrabplus
services:
  webgrabplus:
    image: lscr.io/linuxserver/webgrabplus:latest@sha256:92859e0a4467c77dfae36ec098b41c5b49a5dd503bc0f9ad308e9419ec427c27
    container_name: webgrabplus
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    volumes:
      - type: bind
        source: /DATA/AppData/webgrabplus/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.webgrabplus
  version: "1.0.0"
  main: webgrabplus
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.webgrabplus/assets/icon.svg
  title:
    en_US: "WebGrab+Plus"
  port_map: "0"
  index: /
