name: babybuddy
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:latest@sha256:7441ddeeda783978e63fb3ede3b07fde117a8b1042169022e502b4ca302b3555
    container_name: babybuddy
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8000
        published: "20035"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/babybuddy/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.babybuddy
  version: "1.0.0"
  main: babybuddy
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.babybuddy/assets/icon.png
  title:
    en_US: "Baby Buddy"
  port_map: "20035"
  index: /
