name: planka
services:
  planka:
    image: lscr.io/linuxserver/planka:latest
    container_name: planka
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "BASE_URL=http://zimaos.local:1337"
      - "DATABASE_URL=postgresql://postgres@planka_db/planka"
      - "SECRET_KEY=CHANGE_ME"
    ports:
      - target: 1337
        published: "1337"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/planka/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.planka
  version: "1.0.0"
  main: planka
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.planka/assets/icon.png
  title:
    en_US: "Planka"
  port_map: "1337"
  index: /
