name: signal
services:
  signal:
    image: lscr.io/linuxserver/signal:latest@sha256:587cf340e2a110a18fbb4748c5ef2762124e2cba41eea18ba255fd9585f26620
    container_name: signal
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Signal"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21142"
        protocol: tcp
      - target: 3001
        published: "21143"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.signal
  version: "1.0.1"
  main: signal
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.signal/assets/icon.png
  title:
    en_US: "Signal"
  port_map: "21142"
  index: /
