name: pcsx2
services:
  pcsx2:
    image: lscr.io/linuxserver/pcsx2:latest@sha256:ea8b54f30b4e9e08c26f25583cc62c73ce022c9fe2a94a1f9f9488c64ac13bc8
    container_name: pcsx2
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=PCSX2"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21114"
        protocol: tcp
      - target: 3001
        published: "21115"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pcsx2/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.pcsx2
  version: "1.0.1"
  main: pcsx2
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.pcsx2/assets/icon.png
  title:
    en_US: "PCSX2"
  port_map: "21114"
  index: /
