name: habridge
services:
  habridge:
    image: lscr.io/linuxserver/habridge:latest@sha256:bff25769041c30e109e0f0b616cd3e80bf4022503354c1a0491d340a16acd96f
    container_name: habridge
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8080
        published: "20039"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/habridge/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.habridge
  version: "1.0.0"
  main: habridge
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.habridge/assets/icon.svg
  title:
    en_US: "HA Bridge"
  port_map: "20039"
  index: /
