name: mediaelch
services:
  mediaelch:
    image: lscr.io/linuxserver/mediaelch:latest
    container_name: mediaelch
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=MediaElch"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21096"
        protocol: tcp
      - target: 3001
        published: "21097"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mediaelch/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.mediaelch
  version: "1.0.0"
  main: mediaelch
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.mediaelch/assets/icon.svg
  title:
    en_US: "MediaElch"
  port_map: "21096"
  index: /
