name: librewolf
services:
  librewolf:
    image: lscr.io/linuxserver/librewolf:latest@sha256:d649af4bf3d5acedd8fda7219d366695603d82314cc0e3dd37d0f4aa69916130
    container_name: librewolf
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=LibreWolf"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21090"
        protocol: tcp
      - target: 3001
        published: "21091"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/librewolf/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.librewolf
  version: "1.0.1"
  main: librewolf
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.librewolf/assets/icon.png
  title:
    en_US: "LibreWolf"
  port_map: "21090"
  index: /
