name: budge
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20055"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/budge/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "80"
          description:
            en_US: Port 80/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.budge
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: budge
  author: MrStore
  developer: LinuxServer.io
  category: Productivity
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/budge.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/budge.png
  title:
    en_US: "Budge"
  tagline:
    en_US: "Budge (LinuxServer.io)"
  description:
    en_US: "Budge — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/budge:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-budge/"
  port_map: "20055"
  index: /
