name: webgrabplus
services:
  webgrabplus:
    image: lscr.io/linuxserver/webgrabplus:latest
    container_name: webgrabplus
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    volumes:
      - type: bind
        source: /DATA/AppData/webgrabplus/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.webgrabplus
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: webgrabplus
  author: MrStore
  developer: LinuxServer.io
  category: Media
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/webgrabplus.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/webgrabplus.png
  title:
    en_US: "WebGrab+Plus"
  tagline:
    en_US: "WebGrab+Plus (LinuxServer.io)"
  description:
    en_US: "WebGrab+Plus — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/webgrabplus:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-webgrabplus/"
  port_map: "0"
  index: /
