name: nginx
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20043"
        protocol: tcp
      - target: 443
        published: "20044"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nginx/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "80"
          description:
            en_US: Port 80/tcp
        - container: "443"
          description:
            en_US: Port 443/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.nginx
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: nginx
  author: MrStore
  developer: LinuxServer.io
  category: Developer
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nginx.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nginx.png
  title:
    en_US: "NGINX"
  tagline:
    en_US: "NGINX (LinuxServer.io)"
  description:
    en_US: "NGINX — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/nginx:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-nginx/"
  port_map: "20043"
  index: /
