name: prowlarr
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 9696
        published: "9696"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/prowlarr/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "9696"
          description:
            en_US: Port 9696/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.prowlarr
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: prowlarr
  author: MrStore
  developer: LinuxServer.io
  category: Networking
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png
  title:
    en_US: "Prowlarr"
  tagline:
    en_US: "Prowlarr (LinuxServer.io)"
  description:
    en_US: "Prowlarr — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/prowlarr:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-prowlarr/"
  port_map: "9696"
  index: /
