name: sqlitebrowser
services:
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest@sha256:ca018d756eba0cfc35171a067d894139b74c8ee28ad478bf12b5c6aa0cb34a58
    container_name: sqlitebrowser
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=DB Browser for SQLite"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21146"
        protocol: tcp
      - target: 3001
        published: "21147"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sqlitebrowser/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.sqlitebrowser
  version: "1.0.1"
  main: sqlitebrowser
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.sqlitebrowser/assets/icon.svg
  title:
    en_US: "DB Browser for SQLite"
  port_map: "21146"
  index: /
