name: tvheadend
services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 9981
        published: "9981"
        protocol: tcp
      - target: 9982
        published: "9982"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/tvheadend/config
        target: /config
      - type: bind
        source: /DATA/Media/Recordings
        target: /recordings
x-casaos:
  id: io.github.mrpiracy94.tvheadend
  version: "1.0.1"
  main: tvheadend
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.tvheadend/assets/icon.png
  title:
    en_US: "Tvheadend"
  port_map: "9981"
  index: /
