name: firefox
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Firefox"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21056"
        protocol: tcp
      - target: 3001
        published: "21057"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/firefox/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.firefox
  version: "1.0.1"
  main: firefox
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.firefox/assets/icon.png
  title:
    en_US: "Firefox"
  port_map: "21056"
  index: /
