name: calibre
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest@sha256:fb7a9061bcab2be426f5a1844d841d989936cfd85e5aad74c280fbb7f5d75723
    container_name: calibre
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Calibre"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21028"
        protocol: tcp
      - target: 3001
        published: "21029"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calibre/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.calibre
  version: "1.0.0"
  main: calibre
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.calibre/assets/icon.png
  title:
    en_US: "Calibre"
  port_map: "21028"
  index: /
