name: lychee
services:
  lychee:
    image: lscr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20024"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lychee/config
        target: /config
      - type: bind
        source: /DATA/Gallery
        target: /pictures
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "80"
          description:
            en_US: Port 80/tcp
      volumes:
        - container: /config
          description:
            en_US: /config
        - container: /pictures
          description:
            en_US: /pictures

x-casaos:
  id: io.github.mrpiracy94.lychee
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: lychee
  author: MrStore
  developer: LinuxServer.io
  category: Media
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/lychee.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/lychee.png
  title:
    en_US: "Lychee"
  tagline:
    en_US: "Lychee (LinuxServer.io)"
  description:
    en_US: "Lychee — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/lychee:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-lychee/"
  port_map: "20024"
  index: /
