name: steam
services:
  steam:
    image: lscr.io/linuxserver/steam:latest@sha256:fef0750a876e363d7a943687f5a4daa5778d7223d33e895c585613c1830c4e22
    container_name: steam
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Steam"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21148"
        protocol: tcp
      - target: 3001
        published: "21149"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/steam/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.steam
  version: "1.0.1"
  main: steam
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.steam/assets/icon.png
  title:
    en_US: "Steam"
  port_map: "21148"
  index: /
