name: obsidian
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Obsidian"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21106"
        protocol: tcp
      - target: 3001
        published: "21107"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/obsidian/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.obsidian
  version: "1.0.1"
  main: obsidian
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.obsidian/assets/icon.png
  title:
    en_US: "Obsidian"
  port_map: "21106"
  index: /
