name: keepassxc
services:
  keepassxc:
    image: lscr.io/linuxserver/keepassxc:latest@sha256:a7a914f202f54c927d9cd34b3c28423d2970249d935a605bb74906ede11f85aa
    container_name: keepassxc
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=KeePassXC"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21082"
        protocol: tcp
      - target: 3001
        published: "21083"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/keepassxc/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.keepassxc
  version: "1.0.0"
  main: keepassxc
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.keepassxc/assets/icon.png
  title:
    en_US: "KeePassXC"
  port_map: "21082"
  index: /
