name: duplicati
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest@sha256:4f682e9dd5413a1c3d3412d4be74b67a1ec2650b0bcafcf6df1fb4df8dbee938
    container_name: duplicati
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8200
        published: "8200"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/duplicati/config
        target: /config
      - type: bind
        source: /DATA/Backups
        target: /backups
      - type: bind
        source: /DATA
        target: /source
x-casaos:
  id: io.github.mrpiracy94.duplicati
  version: "1.0.1"
  main: duplicati
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.duplicati/assets/icon.png
  title:
    en_US: "Duplicati"
  port_map: "8200"
  index: /
