name: duplicati
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest@sha256:18648860842107e4db8d3095c5531710abe1d17020555da07d739e50c8dc50e7
    container_name: duplicati
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8200
        published: "8200"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/duplicati/config
        target: /config
      - type: bind
        source: /DATA/Backups
        target: /backups
      - type: bind
        source: /DATA
        target: /source
x-casaos:
  id: io.github.mrpiracy94.duplicati
  version: "1.0.1"
  main: duplicati
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.duplicati/assets/icon.png
  title:
    en_US: "Duplicati"
  port_map: "8200"
  index: /
