name: darktable
services:
  darktable:
    image: lscr.io/linuxserver/darktable:latest
    container_name: darktable
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=darktable"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21038"
        protocol: tcp
      - target: 3001
        published: "21039"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/darktable/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.darktable
  version: "1.0.1"
  main: darktable
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.darktable/assets/icon.svg
  title:
    en_US: "darktable"
  port_map: "21038"
  index: /
