name: handbrake
services:
  handbrake:
    image: lscr.io/linuxserver/handbrake:latest
    container_name: handbrake
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=HandBrake"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21070"
        protocol: tcp
      - target: 3001
        published: "21071"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/handbrake/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.handbrake
  version: "1.0.1"
  main: handbrake
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.handbrake/assets/icon.png
  title:
    en_US: "HandBrake"
  port_map: "21070"
  index: /
