name: beszel
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - target: 8090
        published: "30012"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/beszel
        target: /beszel_data
x-casaos:
  id: io.github.mrpiracy94.beszel
  version: "1.0.1"
  main: beszel
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.beszel/assets/icon.png
  title:
    en_US: "Beszel"
  port_map: "30012"
  index: /
