name: blender
services:
  blender:
    image: lscr.io/linuxserver/blender:latest
    container_name: blender
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Blender"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21022"
        protocol: tcp
      - target: 3001
        published: "21023"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/blender/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.blender
  version: "1.0.1"
  main: blender
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.blender/assets/icon.png
  title:
    en_US: "Blender"
  port_map: "21022"
  index: /
