name: heimdall
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:8ff7b42f1339b9e623bdbf33794f318f926d77d9d1e4d70941a6c82324d6391e
    container_name: heimdall
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/heimdall/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.heimdall
  version: "1.0.1"
  main: heimdall
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.heimdall/assets/icon.png
  title:
    en_US: "Heimdall"
  port_map: "20005"
  index: /
