name: heimdall
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:271a4c6b89ad9a5f7ac0cc97d8c5c56c14727e1f093520eb86b4aa2cc98adfad
    container_name: heimdall
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/heimdall/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.heimdall
  version: "1.0.0"
  main: heimdall
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.heimdall/assets/icon.png
  title:
    en_US: "Heimdall"
  port_map: "20005"
  index: /
