name: heimdall
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:099f15897d0a9992bc8635a63ba120fc7d286f30be4c248a7b480a2810e4d1f5
    container_name: heimdall
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/heimdall/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.heimdall
  version: "1.0.1"
  main: heimdall
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.heimdall/assets/icon.png
  title:
    en_US: "Heimdall"
  port_map: "20005"
  index: /
