name: heimdall
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:c6c8652e82513c6f5c2c157419629ed77719901b56f187abb7adc3a64aa1b779
    container_name: heimdall
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/heimdall/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.heimdall
  version: "1.0.0"
  main: heimdall
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.heimdall/assets/icon.png
  title:
    en_US: "Heimdall"
  port_map: "20005"
  index: /
