name: pelorus
services:
  pelorus:
    image: lscr.io/linuxserver/pelorus:latest
    container_name: pelorus
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "20057"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pelorus/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.pelorus
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: pelorus
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pelorus.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pelorus.png
  title:
    en_US: "Pelorus"
  tagline:
    en_US: "Pelorus (LinuxServer.io)"
  description:
    en_US: "Pelorus — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/pelorus:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-pelorus/"
  port_map: "20057"
  index: /
