name: luanti
services:
  luanti:
    image: lscr.io/linuxserver/luanti:latest@sha256:01a9e19883171befb637a9bfb3089e3e8a3fdf710c4225df37f650947e298a0b
    container_name: luanti
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 30000
        published: "30000"
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/luanti/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.luanti
  version: "1.0.0"
  main: luanti
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.luanti/assets/icon.svg
  title:
    en_US: "Luanti"
  port_map: "0"
  index: /
