name: actual-budget
services:
  actual-budget:
    image: actualbudget/actual-server:latest@sha256:4a65c559c0fb2e667aa6c2cc84b869b4da290419eb870a88724c25e3f02803d7
    container_name: actual-budget
    restart: unless-stopped
    ports:
      - target: 5006
        published: "5006"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/actual-budget
        target: /data
x-casaos:
  id: io.github.mrpiracy94.actual-budget
  version: "1.0.1"
  main: actual-budget
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.actual-budget/assets/icon.png
  title:
    en_US: "Actual Budget"
  port_map: "5006"
  index: /
