name: ardour
services:
  ardour:
    image: lscr.io/linuxserver/ardour:latest@sha256:d482dc4ba93c0e8e71cd78e3beb6584fc5868496067e78e89ed07cb3f5cfdea4
    container_name: ardour
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Ardour"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21014"
        protocol: tcp
      - target: 3001
        published: "21015"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ardour/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.ardour
  version: "1.0.1"
  main: ardour
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.ardour/assets/icon.svg
  title:
    en_US: "Ardour"
  port_map: "21014"
  index: /
