name: flycast
services:
  flycast:
    image: lscr.io/linuxserver/flycast:latest
    container_name: flycast
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Flycast"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21058"
        protocol: tcp
      - target: 3001
        published: "21059"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/flycast/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.flycast
  version: "1.0.1"
  main: flycast
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.flycast/assets/icon.svg
  title:
    en_US: "Flycast"
  port_map: "21058"
  index: /
