name: steamos
services:
  steamos:
    image: lscr.io/linuxserver/steamos:latest
    container_name: steamos
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=SteamOS"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21150"
        protocol: tcp
      - target: 3001
        published: "21151"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/steamos/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.steamos
  version: "1.0.0"
  main: steamos
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.steamos/assets/icon.svg
  title:
    en_US: "SteamOS"
  port_map: "21150"
  index: /
