name: minisatip
services:
  minisatip:
    image: lscr.io/linuxserver/minisatip:latest@sha256:37c1a07cd72643231979b8b3343b105fbde899c68140cee2566c40e68bac1ffe
    container_name: minisatip
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8875
        published: "8875"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/minisatip/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.minisatip
  version: "1.0.1"
  main: minisatip
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.minisatip/assets/icon.png
  title:
    en_US: "minisatip"
  port_map: "8875"
  index: /
