name: minisatip
services:
  minisatip:
    image: lscr.io/linuxserver/minisatip:latest@sha256:b9fd3c9e54e55b82f8d051f6d40efc90e0a4f925601e6458e4e4a4fbd343391b
    container_name: minisatip
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8875
        published: "8875"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/minisatip/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.minisatip
  version: "1.0.0"
  main: minisatip
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.minisatip/assets/icon.svg
  title:
    en_US: "minisatip"
  port_map: "8875"
  index: /
