name: freecad
services:
  freecad:
    image: lscr.io/linuxserver/freecad:latest@sha256:f7045638d01bdc278d9419e9567db0ee33cf753be38765869415d8e3cbe76508
    container_name: freecad
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=FreeCAD"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21060"
        protocol: tcp
      - target: 3001
        published: "21061"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freecad/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.freecad
  version: "1.0.0"
  main: freecad
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.freecad/assets/icon.png
  title:
    en_US: "FreeCAD"
  port_map: "21060"
  index: /
