name: freecad
services:
  freecad:
    image: lscr.io/linuxserver/freecad:latest@sha256:2fe64046b76738c5da5ff089089b475ab711158f3011d6d9ec36f39bdc1f503a
    container_name: freecad
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=FreeCAD"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21060"
        protocol: tcp
      - target: 3001
        published: "21061"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freecad/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.freecad
  version: "1.0.1"
  main: freecad
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.freecad/assets/icon.png
  title:
    en_US: "FreeCAD"
  port_map: "21060"
  index: /
