name: airsonic-advanced
services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-advanced
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 4040
        published: "4040"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/airsonic-advanced/config
        target: /config
      - type: bind
        source: /DATA/Media/Music
        target: /music
      - type: bind
        source: /DATA/Media/Playlists
        target: /playlists
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "4040"
          description:
            en_US: Port 4040/tcp
      volumes:
        - container: /config
          description:
            en_US: /config
        - container: /music
          description:
            en_US: /music
        - container: /playlists
          description:
            en_US: /playlists

x-casaos:
  id: io.github.mrpiracy94.airsonic-advanced
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: airsonic-advanced
  author: MrStore
  developer: LinuxServer.io
  category: Media
  icon: https://raw.githubusercontent.com/mrpiracy94/MrStore/main/Apps/airsonic-advanced/icon.svg
  thumbnail: https://raw.githubusercontent.com/mrpiracy94/MrStore/main/Apps/airsonic-advanced/icon.svg
  title:
    en_US: "Airsonic Advanced"
  tagline:
    en_US: "Airsonic Advanced (LinuxServer.io)"
  description:
    en_US: "Airsonic Advanced — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/airsonic-advanced:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-airsonic-advanced/"
  port_map: "4040"
  index: /
