name: remmina
services:
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Remmina"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21128"
        protocol: tcp
      - target: 3001
        published: "21129"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.remmina
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: remmina
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/remmina.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/remmina.png
  title:
    en_US: "Remmina"
  tagline:
    en_US: "Remmina (LinuxServer.io)"
  description:
    en_US: "Remmina — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/remmina:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-remmina/"
  port_map: "21128"
  index: /
