name: sealskin
services:
  sealskin:
    image: lscr.io/linuxserver/sealskin:latest@sha256:038c26e70cf4b0d874e4f309ec41d6fcf6214f393339f2aa96f08caf4d3c23ff
    container_name: sealskin
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "20058"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sealskin/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.sealskin
  version: "1.0.1"
  main: sealskin
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.sealskin/assets/icon.svg
  title:
    en_US: "SealSkin"
  port_map: "20058"
  index: /
