name: homarr
services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest@sha256:dbc4453cdf0945ea4d04ee6a22e5e46e6aa3bf20cfef659d271a8d2dafcf1ab3
    container_name: homarr
    restart: unless-stopped
    environment:
      - "SECRET_ENCRYPTION_KEY=CHANGE_ME_64_HEX"
    ports:
      - target: 7575
        published: "7575"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/homarr
        target: /appdata
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  id: io.github.mrpiracy94.homarr
  version: "1.0.1"
  main: homarr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.homarr/assets/icon.png
  title:
    en_US: "Homarr"
  port_map: "7575"
  index: /
