name: github-desktop
services:
  github-desktop:
    image: lscr.io/linuxserver/github-desktop:latest@sha256:f705d3bd0062b88122f39a4934157cd2a7b5594d8c9eb05497acf0ab0d48b69d
    container_name: github-desktop
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=GitHub Desktop"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21064"
        protocol: tcp
      - target: 3001
        published: "21065"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/github-desktop/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.github-desktop
  version: "1.0.1"
  main: github-desktop
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.github-desktop/assets/icon.svg
  title:
    en_US: "GitHub Desktop"
  port_map: "21064"
  index: /
