name: tautulli
services:
  tautulli:
    image: ghcr.io/mrpiracy94/mrstore-python-tautulli@sha256:6d9fa8bf48dd804b6b6ba2833a892f2cebfe05ffcbaf365c9474a9efe1c29c8b
    container_name: tautulli
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8181
        published: "8181"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/tautulli/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.tautulli
  version: "1.0.2"
  main: tautulli
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.tautulli/assets/icon.png
  title:
    en_US: "Tautulli"
  port_map: "8181"
  index: /
