name: tautulli
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest@sha256:61c4321a6c3fc846c8dee158b89ef721f5783e01fc32f5d691683b07f1732a55
    container_name: tautulli
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8181
        published: "8181"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/tautulli/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.tautulli
  version: "1.0.0"
  main: tautulli
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.tautulli/assets/icon.png
  title:
    en_US: "Tautulli"
  port_map: "8181"
  index: /
