name: nzbhydra2
services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest@sha256:9e1f67baf493ef58ea534dda55f114bffe6aada281d9fa24d897b3f844dc33a8
    container_name: nzbhydra2
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 5076
        published: "5076"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nzbhydra2/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.nzbhydra2
  version: "1.0.0"
  main: nzbhydra2
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.nzbhydra2/assets/icon.png
  title:
    en_US: "NZBHydra2"
  port_map: "5076"
  index: /
