name: flexget
services:
  flexget:
    image: lscr.io/linuxserver/flexget:latest@sha256:a9de1654939284893f027747cfd7572f5322b79313c4ce9b1b8696c435f37566
    container_name: flexget
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 5050
        published: "5050"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/flexget/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.flexget
  version: "1.0.1"
  main: flexget
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.flexget/assets/icon.png
  title:
    en_US: "FlexGet"
  port_map: "5050"
  index: /
