name: ferdium
services:
  ferdium:
    image: lscr.io/linuxserver/ferdium:latest@sha256:f3da915b00279c847c2302abac63b204b72ee462e26a7ddd3c277302b4ab1a33
    container_name: ferdium
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Ferdium"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21052"
        protocol: tcp
      - target: 3001
        published: "21053"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ferdium/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.ferdium
  version: "1.0.0"
  main: ferdium
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.ferdium/assets/icon.png
  title:
    en_US: "Ferdium"
  port_map: "21052"
  index: /
