name: sonarr
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:09744123b2faed45d701fd1422896015c59837dc60308143240594faa16235f8
    container_name: sonarr
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8989
        published: "8989"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sonarr/config
        target: /config
      - type: bind
        source: /DATA/Media/TV
        target: /tv
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.sonarr
  version: "1.0.1"
  main: sonarr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.sonarr/assets/icon.png
  title:
    en_US: "Sonarr"
  port_map: "8989"
  index: /
