name: organizr
services:
  organizr:
    image: organizr/organizr:latest@sha256:ea71c106e4758fbc1426d3f752a907e137e84260b33473d1061b33d40d07e9e1
    container_name: organizr
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20066"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/organizr/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.organizr
  version: "1.0.1"
  main: organizr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.organizr/assets/icon.png
  title:
    en_US: "Organizr"
  port_map: "20066"
  index: /
