name: webcord
services:
  webcord:
    image: lscr.io/linuxserver/webcord:latest@sha256:034ee2d264859b78aa3c1234d9d401f5c8f712d963c7480b85215ea53fa429fb
    container_name: webcord
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=WebCord"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21164"
        protocol: tcp
      - target: 3001
        published: "21165"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webcord/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.webcord
  version: "1.0.1"
  main: webcord
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.webcord/assets/icon.png
  title:
    en_US: "WebCord"
  port_map: "21164"
  index: /
