name: chrome
services:
  chrome:
    image: lscr.io/linuxserver/chrome:latest@sha256:a7b769aa34af492108145766d9c8fcef55da09a1f717a0ba5c3b646b50ca366d
    container_name: chrome
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Chrome"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21032"
        protocol: tcp
      - target: 3001
        published: "21033"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/chrome/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.chrome
  version: "1.0.1"
  main: chrome
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.chrome/assets/icon.png
  title:
    en_US: "Chrome"
  port_map: "21032"
  index: /
