name: thunderbird
services:
  thunderbird:
    image: lscr.io/linuxserver/thunderbird:latest@sha256:4b779855ae0649ee415c6cc53ce6f246d729ad140c0e25d0c9177bf2dcf982fe
    container_name: thunderbird
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Thunderbird"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21154"
        protocol: tcp
      - target: 3001
        published: "21155"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/thunderbird/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.thunderbird
  version: "1.0.0"
  main: thunderbird
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.thunderbird/assets/icon.png
  title:
    en_US: "Thunderbird"
  port_map: "21154"
  index: /
