name: calligra
services:
  calligra:
    image: lscr.io/linuxserver/calligra:latest@sha256:311d596049f6911dcabe9a39e9bbd38fea0e61a18b0bacdd031038c9db6072ef
    container_name: calligra
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Calligra"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21030"
        protocol: tcp
      - target: 3001
        published: "21031"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calligra/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.calligra
  version: "1.0.1"
  main: calligra
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.calligra/assets/icon.svg
  title:
    en_US: "Calligra"
  port_map: "21030"
  index: /
