name: xbackbone
services:
  xbackbone:
    image: lscr.io/linuxserver/xbackbone:latest@sha256:fb9c36debf75af171d45b5ff40aed588301ec3036d9e413a55eb88b821306020
    container_name: xbackbone
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20023"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/xbackbone/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.xbackbone
  version: "1.0.1"
  main: xbackbone
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.xbackbone/assets/icon.png
  title:
    en_US: "XBackBone"
  port_map: "20023"
  index: /
