name: kicad
services:
  kicad:
    image: lscr.io/linuxserver/kicad:latest@sha256:e760491edf82841b3076339c99d5277e24d569a43b694bde20331e56b7298657
    container_name: kicad
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=KiCad"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21084"
        protocol: tcp
      - target: 3001
        published: "21085"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kicad/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.kicad
  version: "1.0.1"
  main: kicad
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.kicad/assets/icon.svg
  title:
    en_US: "KiCad"
  port_map: "21084"
  index: /
