name: memos
services:
  memos:
    image: neosmemo/memos:stable@sha256:8596928c21551afc7d4e100051510bc134fd0caae51ad1d26cf899845d719321
    container_name: memos
    restart: unless-stopped
    ports:
      - target: 5230
        published: "5230"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/memos
        target: /var/opt/memos
x-casaos:
  id: io.github.mrpiracy94.memos
  version: "1.0.1"
  main: memos
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.memos/assets/icon.png
  title:
    en_US: "Memos"
  port_map: "5230"
  index: /
