name: pidgin
services:
  pidgin:
    image: lscr.io/linuxserver/pidgin:latest
    container_name: pidgin
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Pidgin"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21116"
        protocol: tcp
      - target: 3001
        published: "21117"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pidgin/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.pidgin
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: pidgin
  author: MrStore
  developer: LinuxServer.io
  category: Social
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pidgin.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pidgin.png
  title:
    en_US: "Pidgin"
  tagline:
    en_US: "Pidgin (LinuxServer.io)"
  description:
    en_US: "Pidgin — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/pidgin:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-pidgin/"
  port_map: "21116"
  index: /
