name: doplarr_rs
services:
  doplarr_rs:
    image: lscr.io/linuxserver/doplarr_rs:latest@sha256:ad3b280f5a5821ad2a13634a118045a6e7dbfdefe7422003986c7fe6baab0256
    container_name: doplarr_rs
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    volumes:
      - type: bind
        source: /DATA/AppData/doplarr_rs/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.doplarr_rs
  version: "1.0.2"
  main: doplarr_rs
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.doplarr_rs/assets/icon.svg
  title:
    en_US: "Doplarr RS"
  port_map: "0"
  index: /
