name: zen
services:
  zen:
    image: lscr.io/linuxserver/zen:latest@sha256:8f1e1dfb9134148437c549facbb823b68200821c6af0269eaca6c878bb52468a
    container_name: zen
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Zen Browser"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21178"
        protocol: tcp
      - target: 3001
        published: "21179"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/zen/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.zen
  version: "1.0.2"
  main: zen
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.zen/assets/icon.png
  title:
    en_US: "Zen Browser"
  port_map: "21178"
  index: /
