name: pwndrop
services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest@sha256:14f5255c7bfe033c0bd2b6c33ce1d60abddfc921e2095f188b878786be158f45
    container_name: pwndrop
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8080
        published: "20059"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pwndrop/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.pwndrop
  version: "1.0.0"
  main: pwndrop
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.pwndrop/assets/icon.png
  title:
    en_US: "pwndrop"
  port_map: "20059"
  index: /
