name: gimp
services:
  gimp:
    image: lscr.io/linuxserver/gimp:latest@sha256:0006fe9db865d3d47dddad07e324716e565294e3359407fe12e62a0fd0f2a820
    container_name: gimp
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=GIMP"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21062"
        protocol: tcp
      - target: 3001
        published: "21063"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gimp/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.gimp
  version: "1.0.0"
  main: gimp
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.gimp/assets/icon.png
  title:
    en_US: "GIMP"
  port_map: "21062"
  index: /
