name: wikijs
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest@sha256:540f222f3c8d267ed2c5ffac1b7bf0d6a4dd7352540bd5d44030307095a02f26
    container_name: wikijs
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "20027"
        protocol: tcp
      - target: 3001
        published: "3001"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wikijs/config
        target: /config
      - type: bind
        source: /DATA/AppData/wikijs/data
        target: /data
x-casaos:
  id: io.github.mrpiracy94.wikijs
  version: "1.0.0"
  main: wikijs
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.wikijs/assets/icon.png
  title:
    en_US: "Wiki.js"
  port_map: "20027"
  index: /
