name: zotero
services:
  zotero:
    image: lscr.io/linuxserver/zotero:latest
    container_name: zotero
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Zotero"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21180"
        protocol: tcp
      - target: 3001
        published: "21181"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/zotero/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.zotero
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: zotero
  author: MrStore
  developer: LinuxServer.io
  category: Productivity
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/zotero.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/zotero.png
  title:
    en_US: "Zotero"
  tagline:
    en_US: "Zotero (LinuxServer.io)"
  description:
    en_US: "Zotero — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/zotero:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-zotero/"
  port_map: "21180"
  index: /
