name: stirling-pdf
services:
  stirling-pdf:
    image: docker.io/stirlingtools/stirling-pdf:latest@sha256:0b33f7ed24912de5b65b90ada2b1b42e2abc24f2029f8692adc944a148522f74
    container_name: stirling-pdf
    restart: unless-stopped
    environment:
      - "LANGS=pt_PT"
    ports:
      - target: 8080
        published: "30005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/stirling-pdf/tessdata
        target: /usr/share/tessdata
      - type: bind
        source: /DATA/AppData/stirling-pdf/configs
        target: /configs
x-casaos:
  id: io.github.mrpiracy94.stirling-pdf
  version: "1.0.0"
  main: stirling-pdf
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.stirling-pdf/assets/icon.png
  title:
    en_US: "Stirling PDF"
  port_map: "30005"
  index: /
