name: stirling-pdf
services:
  stirling-pdf:
    image: docker.io/stirlingtools/stirling-pdf:latest@sha256:63859e7302a0533a773655c99071756bbc4a0c710ea3259f1e02671b56cdf8dd
    container_name: stirling-pdf
    restart: unless-stopped
    environment:
      - "LANGS=pt_PT"
    ports:
      - target: 8080
        published: "30005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/stirling-pdf/tessdata
        target: /usr/share/tessdata
      - type: bind
        source: /DATA/AppData/stirling-pdf/configs
        target: /configs
x-casaos:
  id: io.github.mrpiracy94.stirling-pdf
  version: "1.0.1"
  main: stirling-pdf
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.stirling-pdf/assets/icon.png
  title:
    en_US: "Stirling PDF"
  port_map: "30005"
  index: /
