name: kometa
services:
  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    volumes:
      - type: bind
        source: /DATA/AppData/kometa/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.kometa
  version: "1.0.0"
  main: kometa
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.kometa/assets/icon.png
  title:
    en_US: "Kometa"
  port_map: "0"
  index: /
