name: rpcs3
services:
  rpcs3:
    image: lscr.io/linuxserver/rpcs3:latest
    container_name: rpcs3
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=RPCS3"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21132"
        protocol: tcp
      - target: 3001
        published: "21133"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rpcs3/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.rpcs3
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: rpcs3
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/rpcs3-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/rpcs3-logo.png
  title:
    en_US: "RPCS3"
  tagline:
    en_US: "RPCS3 (LinuxServer.io)"
  description:
    en_US: "RPCS3 — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/rpcs3:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-rpcs3/"
  port_map: "21132"
  index: /
