name: spotube
services:
  spotube:
    image: lscr.io/linuxserver/spotube:latest
    container_name: spotube
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Spotube"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21144"
        protocol: tcp
      - target: 3001
        published: "21145"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/spotube/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.spotube
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: spotube
  author: MrStore
  developer: LinuxServer.io
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/spotube-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/c00fb6e6dc50b59217a915188be27d0ea55801c8/linuxserver.io/img/spotube-logo.png
  title:
    en_US: "Spotube"
  tagline:
    en_US: "Spotube (LinuxServer.io)"
  description:
    en_US: "Spotube — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/spotube:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-spotube/"
  port_map: "21144"
  index: /
