name: nextcloud
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest@sha256:2206220ebff0c7838de9e32c2fef4eea07c3322943dd06a3c0ebb872a363d9af
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 443
        published: "20019"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nextcloud/config
        target: /config
      - type: bind
        source: /DATA/AppData/nextcloud/data
        target: /data
x-casaos:
  id: io.github.mrpiracy94.nextcloud
  version: "1.0.1"
  main: nextcloud
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.nextcloud/assets/icon.png
  title:
    en_US: "Nextcloud"
  port_map: "20019"
  index: /
