name: bookstack
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "APP_URL=http://zimaos.local:20026"
      - "APP_KEY=CHANGE_ME"
      - "DB_HOST=CHANGE_ME_DB_HOST"
      - "DB_PORT=3306"
      - "DB_USERNAME=bookstack"
      - "DB_PASSWORD=CHANGE_ME"
      - "DB_DATABASE=bookstackapp"
    ports:
      - target: 80
        published: "20026"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bookstack/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.bookstack
  version: "1.0.2"
  main: bookstack
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.bookstack/assets/icon.png
  title:
    en_US: "BookStack"
  port_map: "20026"
  index: /
