name: manyfold
services:
  manyfold:
    image: lscr.io/linuxserver/manyfold:latest@sha256:33e5889868fa70991b99b15983cf53a15c01f735dab69ca6f06ac1a7b017c112
    container_name: manyfold
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3214
        published: "3214"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/manyfold/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.manyfold
  version: "1.0.1"
  main: manyfold
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.manyfold/assets/icon.png
  title:
    en_US: "Manyfold"
  port_map: "3214"
  index: /
