name: sealskin
services:
  sealskin:
    image: lscr.io/linuxserver/sealskin:latest
    container_name: sealskin
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "20058"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sealskin/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.sealskin
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: sealskin
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://raw.githubusercontent.com/selkies-project/sealskin/d054d878d00ad22893c1c9a07b2c1c2638e626b9/docs/app/icon.png
  thumbnail: https://raw.githubusercontent.com/selkies-project/sealskin/d054d878d00ad22893c1c9a07b2c1c2638e626b9/docs/app/icon.png
  title:
    en_US: "SealSkin"
  tagline:
    en_US: "SealSkin (LinuxServer.io)"
  description:
    en_US: "SealSkin — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/sealskin:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-sealskin/"
  port_map: "20058"
  index: /
