name: gitea
services:
  gitea:
    image: docker.io/gitea/gitea:latest@sha256:1de3b99b9e3e080ba73b4028324b425274ad00d676803603f7f19efdc416045b
    container_name: gitea
    restart: unless-stopped
    environment:
      - "USER_UID=1000"
      - "USER_GID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "30000"
        protocol: tcp
      - target: 22
        published: "30001"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gitea
        target: /data
x-casaos:
  id: io.github.mrpiracy94.gitea
  version: "1.0.1"
  main: gitea
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.gitea/assets/icon.png
  title:
    en_US: "Gitea"
  port_map: "30000"
  index: /
