name: dogwalk
services:
  dogwalk:
    image: lscr.io/linuxserver/dogwalk:latest@sha256:c18d5f68ff8fe53f77743e3a0578f08888d33b111af7d7a4410c37d98d198488
    container_name: dogwalk
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Dogwalk"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21006"
        protocol: tcp
      - target: 3001
        published: "21007"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dogwalk/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.dogwalk
  version: "1.0.1"
  main: dogwalk
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.dogwalk/assets/icon.png
  title:
    en_US: "Dogwalk"
  port_map: "21006"
  index: /
