name: librespeed
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20009"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/librespeed/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "80"
          description:
            en_US: Port 80/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.librespeed
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: librespeed
  author: MrStore
  developer: LinuxServer.io
  category: Networking
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/librespeed.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/librespeed.png
  title:
    en_US: "LibreSpeed"
  tagline:
    en_US: "LibreSpeed (LinuxServer.io)"
  description:
    en_US: "LibreSpeed — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/librespeed:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-librespeed/"
  port_map: "20009"
  index: /
