name: unpackerr
services:
  unpackerr:
    image: golift/unpackerr:latest@sha256:5b4589fd9153a9468502efbc9148b3c1d9a3678299c40c244accaf34f81f584b
    container_name: unpackerr
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.unpackerr
  version: "1.0.0"
  main: unpackerr
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.unpackerr/assets/icon.png
  title:
    en_US: "Unpackerr"
  port_map: "0"
  index: /
