name: emby
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8096
        published: "20003"
        protocol: tcp
      - target: 8920
        published: "20004"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/emby/config
        target: /config
      - type: bind
        source: /DATA/Media/TV
        target: /data/tvshows
      - type: bind
        source: /DATA/Media/Movies
        target: /data/movies
x-casaos:
  id: io.github.mrpiracy94.emby
  version: "1.0.0"
  main: emby
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.emby/assets/icon.png
  title:
    en_US: "Emby"
  port_map: "20003"
  index: /
