name: bitcoin-knots
services:
  bitcoin-knots:
    image: lscr.io/linuxserver/bitcoin-knots:latest
    container_name: bitcoin-knots
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8333
        published: "8333"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bitcoin-knots/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "8333"
          description:
            en_US: Port 8333/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.bitcoin-knots
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: bitcoin-knots
  author: MrStore
  developer: LinuxServer.io
  category: Developer
  icon: https://raw.githubusercontent.com/mrpiracy94/MrStore/main/Apps/bitcoin-knots/icon.svg
  thumbnail: https://raw.githubusercontent.com/mrpiracy94/MrStore/main/Apps/bitcoin-knots/icon.svg
  title:
    en_US: "Bitcoin Knots"
  tagline:
    en_US: "Bitcoin Knots (LinuxServer.io)"
  description:
    en_US: "Bitcoin Knots — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/bitcoin-knots:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-bitcoin-knots/"
  port_map: "0"
  index: /
