name: mealie
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest@sha256:1994d77ab18293108c449f2429fdf7877f69d56b61110da16812902223fbff7d
    container_name: mealie
    restart: unless-stopped
    environment:
      - "ALLOW_SIGNUP=false"
      - "BASE_URL=http://zimaos.local:9925"
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 9000
        published: "30015"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mealie
        target: /app/data
x-casaos:
  id: io.github.mrpiracy94.mealie
  version: "1.0.1"
  main: mealie
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.mealie/assets/icon.png
  title:
    en_US: "Mealie"
  port_map: "30015"
  index: /
