name: doublecommander
services:
  doublecommander:
    image: lscr.io/linuxserver/doublecommander:latest
    container_name: doublecommander
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Double Commander"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21046"
        protocol: tcp
      - target: 3001
        published: "21047"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/doublecommander/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.doublecommander
  version: "1.0.0"
  main: doublecommander
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.doublecommander/assets/icon.svg
  title:
    en_US: "Double Commander"
  port_map: "21046"
  index: /
