name: vscodium-web
services:
  vscodium-web:
    image: lscr.io/linuxserver/vscodium-web:latest@sha256:97dc4d04e42c8d89a060df80ee48c98bf1965ab75669a59257bc393e059d3026
    container_name: vscodium-web
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "20047"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium-web/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.vscodium-web
  version: "1.0.1"
  main: vscodium-web
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.vscodium-web/assets/icon.svg
  title:
    en_US: "VSCodium Web"
  port_map: "20047"
  index: /
