name: ppsspp
services:
  ppsspp:
    image: lscr.io/linuxserver/ppsspp:latest@sha256:cb330d319d159555d2c2f807768625f47c07490087e7516a2144f83926653d4b
    container_name: ppsspp
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=PPSSPP"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21118"
        protocol: tcp
      - target: 3001
        published: "21119"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ppsspp/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.ppsspp
  version: "1.0.0"
  main: ppsspp
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.ppsspp/assets/icon.svg
  title:
    en_US: "PPSSPP"
  port_map: "21118"
  index: /
