name: azahar
services:
  azahar:
    image: lscr.io/linuxserver/azahar:latest
    container_name: azahar
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Azahar"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21018"
        protocol: tcp
      - target: 3001
        published: "21019"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/azahar/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.azahar
  version: "1.0.1"
  main: azahar
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.azahar/assets/icon.svg
  title:
    en_US: "Azahar"
  port_map: "21018"
  index: /
