name: qdirstat
services:
  qdirstat:
    image: lscr.io/linuxserver/qdirstat:latest@sha256:801140de1dda08bfd7762404264c520ed78c34165261431e49a07039cfad7fda
    container_name: qdirstat
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=QDirStat"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21122"
        protocol: tcp
      - target: 3001
        published: "21123"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/qdirstat/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.qdirstat
  version: "1.0.0"
  main: qdirstat
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.qdirstat/assets/icon.png
  title:
    en_US: "QDirStat"
  port_map: "21122"
  index: /
