name: beets
services:
  beets:
    image: lscr.io/linuxserver/beets:latest@sha256:fd4e826c8d44a62fe1bc37a4e33121ebdb19f8d16497ef7416b652a38d4da5b9
    container_name: beets
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8337
        published: "8337"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/beets/config
        target: /config
      - type: bind
        source: /DATA/Media/Music
        target: /music
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.beets
  version: "1.0.1"
  main: beets
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.beets/assets/icon.png
  title:
    en_US: "Beets"
  port_map: "8337"
  index: /
