name: beets
services:
  beets:
    image: ghcr.io/mrpiracy94/mrstore-python-beets@sha256:731e25db040b766afade34c113195d361575806de141f6b1227447ae64ad1ab0
    container_name: beets
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 8337
        published: "8337"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/beets/config
        target: /config
      - type: bind
        source: /DATA/Media/Music
        target: /music
      - type: bind
        source: /DATA/Downloads
        target: /downloads
x-casaos:
  id: io.github.mrpiracy94.beets
  version: "1.0.2"
  main: beets
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.beets/assets/icon.png
  title:
    en_US: "Beets"
  port_map: "8337"
  index: /
