name: pycharm
services:
  pycharm:
    image: lscr.io/linuxserver/pycharm:latest@sha256:5a0555bc8862b8fa35908021d005be95f8b4ba09e21fde37678ffd20014153e0
    container_name: pycharm
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=PyCharm"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21120"
        protocol: tcp
      - target: 3001
        published: "21121"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pycharm/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.pycharm
  version: "1.0.0"
  main: pycharm
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.pycharm/assets/icon.svg
  title:
    en_US: "PyCharm"
  port_map: "21120"
  index: /
