name: kdenlive
services:
  kdenlive:
    image: lscr.io/linuxserver/kdenlive:latest
    container_name: kdenlive
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Kdenlive"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21080"
        protocol: tcp
      - target: 3001
        published: "21081"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kdenlive/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.kdenlive
  version: "1.0.0"
  main: kdenlive
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.kdenlive/assets/icon.svg
  title:
    en_US: "Kdenlive"
  port_map: "21080"
  index: /
