name: bambustudio
services:
  bambustudio:
    image: lscr.io/linuxserver/bambustudio:latest
    container_name: bambustudio
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Bambu Studio"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21020"
        protocol: tcp
      - target: 3001
        published: "21021"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bambustudio/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.bambustudio
  version: "1.0.2"
  main: bambustudio
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.bambustudio/assets/icon.png
  title:
    en_US: "Bambu Studio"
  port_map: "21020"
  index: /
