name: ungoogled-chromium
services:
  ungoogled-chromium:
    image: lscr.io/linuxserver/ungoogled-chromium:latest@sha256:7055390b8970e153abdb199de885334a70d3bb26c1658ba1fc0572a6965a7cfa
    container_name: ungoogled-chromium
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Ungoogled Chromium"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21156"
        protocol: tcp
      - target: 3001
        published: "21157"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ungoogled-chromium/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.ungoogled-chromium
  version: "1.0.1"
  main: ungoogled-chromium
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.ungoogled-chromium/assets/icon.svg
  title:
    en_US: "Ungoogled Chromium"
  port_map: "21156"
  index: /
