name: socket-proxy
services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "CONTAINERS=1"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      volumes:
        - container: /var/run/docker.sock
          description:
            en_US: /var/run/docker.sock

x-casaos:
  id: io.github.mrpiracy94.socket-proxy
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: socket-proxy
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/socket-proxy.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/socket-proxy.png
  title:
    en_US: "Socket Proxy"
  tagline:
    en_US: "Socket Proxy (LinuxServer.io)"
  description:
    en_US: "Socket Proxy — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/socket-proxy:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-socket-proxy/"
  port_map: "0"
  index: /
