name: helium
services:
  helium:
    image: lscr.io/linuxserver/helium:latest
    container_name: helium
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Helium"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21072"
        protocol: tcp
      - target: 3001
        published: "21073"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/helium/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.helium
  version: "1.0.1"
  main: helium
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.helium/assets/icon.svg
  title:
    en_US: "Helium"
  port_map: "21072"
  index: /
