name: audacity
services:
  audacity:
    image: lscr.io/linuxserver/audacity:latest@sha256:ab533efcffff7c0fd27dbd4c19e085cbd9ab405db5f72802a678c312a0c46ec6
    container_name: audacity
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Audacity"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21016"
        protocol: tcp
      - target: 3001
        published: "21017"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/audacity/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.audacity
  version: "1.0.1"
  main: audacity
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.audacity/assets/icon.png
  title:
    en_US: "Audacity"
  port_map: "21016"
  index: /
