name: healthchecks
services:
  healthchecks:
    image: ghcr.io/mrpiracy94/mrstore-healthchecks@sha256:32c4096680c75431b0e7c20a0064f3e54b25cf55e67c012092f29d1fe61b4b81
    container_name: healthchecks
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "SECRET_KEY=CHANGE_ME_SECRET_KEY"
      - "SITE_ROOT=http://zimaos.local:20037"
      - "SITE_NAME=Healthchecks"
      - "SUPERUSER_EMAIL=CHANGE_ME_EMAIL"
      - "SUPERUSER_PASSWORD=CHANGE_ME"
    ports:
      - target: 8000
        published: "20037"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/healthchecks/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.healthchecks
  version: "1.0.3"
  main: healthchecks
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.healthchecks/assets/icon.png
  title:
    en_US: "Healthchecks"
  port_map: "20037"
  index: /
