name: dolphin
services:
  dolphin:
    image: lscr.io/linuxserver/dolphin:latest
    container_name: dolphin
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Dolphin Emulator"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21042"
        protocol: tcp
      - target: 3001
        published: "21043"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dolphin/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "3000"
          description:
            en_US: Port 3000/tcp
        - container: "3001"
          description:
            en_US: Port 3001/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.dolphin
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
  main: dolphin
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/dolphin.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/dolphin.png
  title:
    en_US: "Dolphin Emulator"
  tagline:
    en_US: "Dolphin Emulator (LinuxServer.io)"
  description:
    en_US: "Dolphin Emulator — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/dolphin:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-dolphin/"
  port_map: "21042"
  index: /
