name: esphome
services:
  esphome:
    image: ghcr.io/esphome/esphome:latest@sha256:47d3a747b958eb798a9d246726e1526d4143fb85ba864e13c5558e4f067bdcfe
    container_name: esphome
    restart: unless-stopped
    environment:
      - "TZ=Europe/Lisbon"
    ports:
      - target: 6052
        published: "6052"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/esphome
        target: /config
x-casaos:
  id: io.github.mrpiracy94.esphome
  version: "1.0.0"
  main: esphome
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.esphome/assets/icon.png
  title:
    en_US: "ESPHome"
  port_map: "6052"
  index: /
