name: rsnapshot
services:
  rsnapshot:
    image: lscr.io/linuxserver/rsnapshot:latest
    container_name: rsnapshot
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    volumes:
      - type: bind
        source: /DATA/AppData/rsnapshot/config
        target: /config
      - type: bind
        source: /DATA/Backups/snapshots
        target: /snapshots
      - type: bind
        source: /DATA
        target: /data
x-casaos:
  id: io.github.mrpiracy94.rsnapshot
  version: "1.0.1"
  main: rsnapshot
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.rsnapshot/assets/icon.png
  title:
    en_US: "rsnapshot"
  port_map: "0"
  index: /
