name: heimdall
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/heimdall/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone
      ports:
        - container: "80"
          description:
            en_US: Port 80/tcp
      volumes:
        - container: /config
          description:
            en_US: /config

x-casaos:
  id: io.github.mrpiracy94.heimdall
  version: "1.0.0"
  update_at: "2026-10-09"
  architectures:
    - amd64
    - arm64
  main: heimdall
  author: MrStore
  developer: LinuxServer.io
  category: Others
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/heimdall.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/heimdall.png
  title:
    en_US: "Heimdall"
  tagline:
    en_US: "Heimdall (LinuxServer.io)"
  description:
    en_US: "Heimdall — origem: LinuxServer.io. Imagem: lscr.io/linuxserver/heimdall:latest. Verifica portas/variáveis na documentação do projeto. Docs: https://docs.linuxserver.io/images/docker-heimdall/"
  port_map: "20005"
  index: /
