name: spotube
services:
  spotube:
    image: lscr.io/linuxserver/spotube:latest@sha256:9b8183147a15ede111baa33e05e93c4fc1736c2dafd05a0aa3b7e329ba32570a
    container_name: spotube
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Spotube"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21144"
        protocol: tcp
      - target: 3001
        published: "21145"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/spotube/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.spotube
  version: "1.0.1"
  main: spotube
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.spotube/assets/icon.png
  title:
    en_US: "Spotube"
  port_map: "21144"
  index: /
