name: weixin
services:
  weixin:
    image: lscr.io/linuxserver/weixin:latest@sha256:43b6b74e3627dc9f08412c39266ae5567081da88116a12b77d8af21d0aafd263
    container_name: weixin
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Weixin"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21168"
        protocol: tcp
      - target: 3001
        published: "21169"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/weixin/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.weixin
  version: "1.0.0"
  main: weixin
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.weixin/assets/icon.svg
  title:
    en_US: "Weixin"
  port_map: "21168"
  index: /
