name: nginx
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest@sha256:5fc7ae64b7c1d8f4e658dbd9801f22a86c8a039d2f26e4c4f856e62711387bde
    container_name: nginx
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20043"
        protocol: tcp
      - target: 443
        published: "20044"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nginx/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.nginx
  version: "1.0.1"
  main: nginx
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.nginx/assets/icon.png
  title:
    en_US: "NGINX"
  port_map: "20043"
  index: /
