name: nginx
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest@sha256:7743abf7d8fb55f96d2f9eabf0c3988101af6bc4f1556e2da3bd5a1d5745eab8
    container_name: nginx
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 80
        published: "20043"
        protocol: tcp
      - target: 443
        published: "20044"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nginx/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.nginx
  version: "1.0.0"
  main: nginx
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.nginx/assets/icon.png
  title:
    en_US: "NGINX"
  port_map: "20043"
  index: /
