name: kimai
services:
  kimai:
    image: lscr.io/linuxserver/kimai:latest@sha256:a8180344fd2585b95be1c667314584b8dd9b4c3be1b62fbf7e2026fe82a3e062
    container_name: kimai
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "ADMINMAIL=admin@example.com"
      - "ADMINPASS=CHANGE_ME"
      - "DATABASE_URL=sqlite:///var/data/kimai.sqlite"
    ports:
      - target: 8001
        published: "8001"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kimai/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.kimai
  version: "1.0.1"
  main: kimai
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.kimai/assets/icon.png
  title:
    en_US: "Kimai"
  port_map: "8001"
  index: /
