name: intellij-idea
services:
  intellij-idea:
    image: lscr.io/linuxserver/intellij-idea:latest
    container_name: intellij-idea
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=IntelliJ IDEA"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21076"
        protocol: tcp
      - target: 3001
        published: "21077"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/intellij-idea/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.intellij-idea
  version: "1.0.2"
  main: intellij-idea
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.intellij-idea/assets/icon.svg
  title:
    en_US: "IntelliJ IDEA"
  port_map: "21076"
  index: /
