name: zotero
services:
  zotero:
    image: lscr.io/linuxserver/zotero:latest
    container_name: zotero
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=Zotero"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21180"
        protocol: tcp
      - target: 3001
        published: "21181"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/zotero/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.zotero
  version: "1.0.0"
  main: zotero
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.zotero/assets/icon.png
  title:
    en_US: "Zotero"
  port_map: "21180"
  index: /
