name: retroarch
services:
  retroarch:
    image: lscr.io/linuxserver/retroarch:latest@sha256:d8295a342d77c7adf0844919b11c9addb5494e109163f88062981a4d939b8e8e
    container_name: retroarch
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
      - "TITLE=RetroArch"
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    ports:
      - target: 3000
        published: "21130"
        protocol: tcp
      - target: 3001
        published: "21131"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/retroarch/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.retroarch
  version: "1.0.1"
  main: retroarch
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.retroarch/assets/icon.svg
  title:
    en_US: "RetroArch"
  port_map: "21130"
  index: /
