name: raneto
services:
  raneto:
    image: lscr.io/linuxserver/raneto:latest
    container_name: raneto
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    ports:
      - target: 3000
        published: "20030"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/raneto/config
        target: /config
x-casaos:
  id: io.github.mrpiracy94.raneto
  version: "1.0.1"
  main: raneto
  icon: https://mrpiracy94.github.io/MrStore/apps/io.github.mrpiracy94.raneto/assets/icon.png
  title:
    en_US: "Raneto"
  port_map: "20030"
  index: /
